"""Initial setup

Revision ID: 217dc1f549a0
Revises: 
Create Date: 2025-02-06 19:10:07.063762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217dc1f549a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabular_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabular_data')
    # ### end Alembic commands ###
